name: myenv

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - pandas
  - opencv=4.5.1
  - cherrypy
  - configparser
  - adafruit-circuitpython-neopixel
  - blinker
  - jinja2
  - sounddevice
  - pyaudio
